apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kruize
  labels:
    team: kruize-frontend
spec:
  selector:
    matchLabels:
      app: kruize
  endpoints:
  - port: http
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: kruize-frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
