{
 "title": "Kruize Dashboard",
 "tags": [ "CBolt" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{namespace=~\"$namespace\"},deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kruize_exp_original_cpu_requests{application_name=~\"$deployment\"}",
     "legendFormat": "Original "
    },
    {
     "expr": "kruize_exp_cpu_requests{application_name=~\"$deployment\"}",
     "legendFormat": "Recommended "
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kruize_exp_original_cpu_limits{application_name=~\"$deployment\"}",
     "legendFormat": "Original "
    },
    {
     "expr": "kruize_exp_cpu_limits{application_name=~\"$deployment\"}",
     "legendFormat": "Recommended"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kruize_exp_original_memory_requests{application_name=~\"$deployment\"}",
     "legendFormat": "Original "
    },
    {
     "expr": "kruize_exp_memory_requests{application_name=~\"$deployment\"}",
     "legendFormat": "Recommended "
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kruize_exp_original_memory_limits{application_name=~\"$deployment\"}",
     "legendFormat": "Original "
    },
    {
     "expr": "kruize_exp_memory_limits{application_name=~\"$deployment\"}",
     "legendFormat": "Recommended"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kruize_exp_application_cpu_current{application_name=~\"$deployment\"}",
     "legendFormat": "Current CPU Usage"
    },
    {
     "expr": "kruize_exp_original_cpu_requests{application_name=~\"$deployment\"}",
     "legendFormat": "Original CPU Request"
    },
    {
     "expr": "kruize_exp_cpu_requests{application_name=~\"$deployment\"}",
     "legendFormat": "Recommended CPU Request"
    },
    {
     "expr": "kruize_exp_original_cpu_limits{application_name=~\"$deployment\"}",
     "legendFormat": "Original CPU Limit"
    },
    {
     "expr": "kruize_exp_cpu_limits{application_name=~\"$deployment\"}",
     "legendFormat": "Recommended CPU Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kruize_exp_application_rss_current{application_name=~\"$deployment\"}",
     "legendFormat": "Current Memory Usage"
    },
    {
     "expr": "kruize_exp_original_memory_requests{application_name=~\"$deployment\"}",
     "legendFormat": "Original Memory Request"
    },
    {
     "expr": "kruize_exp_memory_requests{application_name=~\"$deployment\"}",
     "legendFormat": "Recommended Memory Request"
    },
    {
     "expr": "kruize_exp_original_memory_limits{application_name=~\"$deployment\"}",
     "legendFormat": "Original Memory Limit"
    },
    {
     "expr": "kruize_exp_memory_limits{application_name=~\"$deployment\"}",
     "legendFormat": "Recommended Memory Limit"
    }
   ]
  }
 ]
}